### ISSUE TITLE
Can not bind selected value

### ISSUE THREAD

**Issue by kaushaldevluk** [Oceanware/XamarinFormsBindablePicker#1]
i used selected value and it can not bind it my code is 

<controls:BindablePicker
            Title="Select System Element"
            TextColor="White"
            DisplayMemberPath="SystemElementName"
            SelectedValuePath="SystemElementID"
                    ItemsSource="{Binding SystemElementList}"
                    SelectedValue="{Binding Path=SESelectedValue, Mode=TwoWay}" />

**Comment by kdawg1406** [comment]
Your code has:
`SelectedValue="{Binding Path=SESelectedValue, Mode=TwoWay}" />`

Your binding path starts with "**SES**" is that the name of the property?

Do you have any data binding errors in the output window when you run your application in Debug mode?

If the above is correct, can you post your project on GitHub?

Best,

Karl

**Comment by kaushaldevluk** [comment]
the cs file is :
 public IEnumerable<SystemElement> SystemElementList { get; set; }
        public int SESelectedValue { get; set; }
        public IList<Material> MaterialList { get; set; }
        public int MATSelectedValue { get; set; }
      

        public ProjectScreenBeforeViewModal()
        {
            
            tblSystemElement _tblSystemElement = new tblSystemElement();
            SystemElementList = _tblSystemElement.GetAll();
            SESelectedValue = 1;
            tblMaterial _tblMaterial = new tblMaterial();
            MaterialList = _tblMaterial.GetAll();
            
                Building build = new Building();
                tblBuilding dbbuild = new tblBuilding();
                build = dbbuild.Get(ID);
                _LocationID = build.LocationID;

                //build.BuildingSystemID = BSSelectedValue;
                SESelectedValue = 1;
                
                _detail = build.Details;
               
                _height = build.Height;
                _width = build.Width;
                MATSelectedValue = build.MaterialID;
              
            }

        }


and the xaml file is:

<Label Text="System Element" TextColor="#00d0d2"></Label>
      <controls:BindablePicker
            Title="Select System Element"
            TextColor="White"
            DisplayMemberPath="SystemElementName"
            SelectedValuePath="SystemElementID"
                    ItemsSource="{Binding SystemElementList}"
                    SelectedValue="{Binding Path=SESelectedValue, Mode=TwoWay}" />

     

      <Label Text="Material" TextColor="#00d0d2"></Label>
      <controls:BindablePicker
            Title="Select Material"
            TextColor="White"
            DisplayMemberPath="MaterialName"
            SelectedValuePath="MaterialID"
                    ItemsSource="{Binding MaterialList}"
                    SelectedValue="{Binding Path=MATSelectedValue, Mode=TwoWay}" />

**Comment by kdawg1406** [comment]
Do you have any data binding warnings or errors in the VS output window when you run the project in debug mode?

What types are in the MaterialList?  

Please post this project or a simple repro on GitHub so I can help you.

**Comment by kaushaldevluk** [comment]
i can not get any errors in VS output when run the project in debug mode 
and the type of MaterialList and SystemElement List is:

        public IEnumerable<SystemElement> SystemElementList { get; set; }
        public int SESelectedValue { get; set; }
        public IEnumerable<Material> MaterialList { get; set; }
        public int MATSelectedValue { get; set; }

**Comment by kdawg1406** [comment]
Please post a simple project on GitHub so I can help you.

**Comment by kaushaldevluk** [comment]
https://github.com/kaushaldevluk/PPMBindablePickerIssue

i upload it on this link please help me to fix it
Bindable picker set on ProjectScreenBefore in view Folder 
or its viewModal in ProjectScreenBeforeViewModal

Thank You So Much

**Comment by kdawg1406** [comment]
The BindablePicker control you are using is the original version.

Please update your BindablePicker control to the one in this repro.

https://github.com/Oceanware/XamarinFormsBindablePicker/blob/master/XamarinFormsBindablePicker/XamarinFormsBindablePicker/Controls/BindablePicker.cs

**Comment by kdawg1406** [comment]
This blog post covered the new BindablePicker:  https://oceanware.wordpress.com/2016/08/12/xamarin-forms-bindable-picker-v2/

**Comment by kaushaldevluk** [comment]
i try that then also it not working

**Comment by kaushaldevluk** [comment]
kaushal.avyak@gmail.com is my skype email address can we meet on there ?

**Comment by kdawg1406** [comment]
I can't run you project.

You are **not** implementing INotifyPropertyChanged in your ProjectScreenBeforeViewModal.  This is probably your problem.  All properties that are binding two-way require this.

What EXACTLY is not working?  

Have you run the project in this repro?  This works.

I suggest you look at this repro project and follow how I set up the view model and collections.

If you still can't get your project to work, please make a simple project that will run without a database and I can help you get your usage of the BindablePicker working.

**Comment by kaushaldevluk** [comment]
https://github.com/kaushaldevluk/PPMBindablePickerIssue/tree/master/BindablePicker


in same repro i create my demo please see that help me

**Comment by kaushaldevluk** [comment]
https://github.com/kaushaldevluk/BindablePickerTestDemo

my demo repro

**Comment by kdawg1406** [comment]
I found a problem that I need to speak with Microsoft about.

For now, here is a workaround.  Change the data type of the selected value property to string. In your case "SystemElementID" to a string and the SESelectedValue to string.

Or, use the Picker control that comes with Xamarin Forms until I get this resolved.

I'll let you know when I've posted an update.

Apologies for the trouble.

Karl

**Comment by kaushaldevluk** [comment]
ok no problem i try as you suggest

**Comment by kaushaldevluk** [comment]
i try to use string instead of int but problem can not resolve

thank you so much for help me

**Comment by kaushaldevluk** [comment]
do you know how to call method on bindablepicker index change event ??

**Comment by kdawg1406** [comment]
not sure I understand the question.  I thought you were going to use the Picker control.

**Comment by kdawg1406** [comment]
@kaushaldevluk I corrected the bug.  I have also updated the sample project to use an Int32 for the Country Id to match your scenario.

1.  Update you BindablePicker code to use the corrected on in this release.
2.  Download this sample and run it.  You'll see it works correctly.
3.  Update your ViewModel and other code to match the pattern in this sample, your scenario will work now.

Best,

Karl

**Comment by kaushaldevluk** [comment]
ok thank you so much
