### ISSUE TITLE
ObservableRangeCollection Enhancement

### ISSUE THREAD

**Issue by Pinox** [Oceanware/XamarinFormsBindablePicker#2]
Thanks for a great control.  It would be nice to expand the funtionality to include ObservableRangeCollection.

Therefor instead of adding individual items to the ObservableCollection  you can use the 
ObservableRangeCollection.ReplaceRange ( List <items> )  to add all items at once and only fire the change event once.

**Comment by kdawg1406** [comment]
@Pinox would be glad to.  Can you provide a little more detail and I'll do it later today.  Thanks.

**Comment by Pinox** [comment]
I like to use ObservableRangeCollection instead of ObservableCollection for the stated reason above.

I tested the picker with ObservableRangeCollection but it did not seem to work => therefor i switched to ObservableCollection and that works fine.

I just think adding say 50 items to a picker using ObservableCollection is slightly inefficient as 50 events will be fired instead of the 1 event in ObservableRangeCollection.  

code will be 
ObservableRangeCollection.AddRange( List) versus the current ObservableRangeCollection.Add( item )

**Comment by kdawg1406** [comment]
@Pinox very good point.  Let me look into supporting ObservableRangeCollection as well as ObservableCollection.

**Comment by Pinox** [comment]
Sorry , i forgot to mention that the ObservableRangeCollection is one of the Mvvm Helpers of James Montemagno.

https://github.com/jamesmontemagno/mvvm-helpers
http://stackoverflow.com/questions/38110580/how-to-convert-listobjects-to-an-observablerangecollection

**Comment by kdawg1406** [comment]
@Pinox OK, now I understand why I've never heard of this.  

I can't take a dependency on this.  However, you can make your own build of XAML Power Toys.

Best,

Karl

**Comment by Pinox** [comment]
Was thinking you can just include the ObservableRangeCollection source in your project without referencing a lib. I think it only 107 lines of code : 
https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/ObservableRangeCollection.cs

**Comment by kdawg1406** [comment]
@Pinox would rather not, I would be opening up myself to other similar requests.  Better to just make your own private build.

**Comment by kdawg1406** [comment]
@Pinox I've been thinking about how to support this in a general way.  

Do you have a simple repo project you can post on github?  Thanks for posting a project, I'll dig into it.

**Comment by Pinox** [comment]
Hi Karl,

Link to sample project : https://drive.google.com/open?id=0B0Gm-m-z_U84UzVJVWhkaEJTU28

I noticed that the clear method on the ObservableCollection does not work either.

**Comment by Pinox** [comment]
Hi Karl,

Plse find sample app on Picker  : https://drive.google.com/open?id=0B0Gm-m-z_U84dzdZOFJuMHQ1Vms

I used ReplaceRange in my collection , changing that to addrange i managed to get the ObservableRangeCollection to work with your bindable picker but i have problems clearing the items of the ObservableCollection and the ObservableRangeCollection.  The items in the collection are cleared in the viewmodel but the UI does not display the updated items.  

I guess the UI bindable picker will also not change if the Observable Collections change in the viewmodel.

**Comment by kdawg1406** [comment]
@Pinox I'll look at the Clear Items issue Thursday afternoon.  Thank you for reporting this.

**Comment by kdawg1406** [comment]
@Pinox I've correct the items clearing issue.  Just checked in the fix.  Thank you for pointing this out.

Best,

Karl
